=head1 Name

lua-oocairo-fontface - Unscaled font face object

=head1 Introduction

Cairo font face objects are returned by the C<get_font_face> method
on context objects (see L<lua-oocairo-context(3)>).  They represent
a font selection, but not including the scaling used to create a
font of a particular size.

Font face objects can be compared with the C<==> operator.  This will compare
the identity of the objects, so different Lua objects which refer to the
same C<cairo_font_face_t> will compare as equal.

=head1 Methods

Font face objects currently only provide one method:

=over

=item fontface:get_type ()

Returns a string indicating what backend library handles this font.
The return value will be one of the following:

=over

=item toy

Created using Cairo's ‘toy’ font API, probably selected with
the C<select_font_face> method.

=item ft

Created with the FreeType API.

=item win32

A Windows native font.

=item quartz

A MacOS X native font.

=item user

A font created with custom code.

=back

=back

=for comment
vi:ts=4 sw=4 expandtab
